import type { PipelineResults, ReagentInfo, SynthesisRoute } from '@/types/chemtrace';

function downloadBlob(content: string, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}

export function downloadRoutesCSV(results: PipelineResults) {
  const header = 'Route ID,Name,Status,Score,Yield %,Cost/g (£),Batch Estimate (£),Steps,Supply Risk,Regulatory Risk\n';
  const rows = results.routes.map(r =>
    `${r.id},"${r.name}",${r.status},${r.score},${r.yieldPercent},${r.costPerGram},${r.batchEstimate},${r.steps.length},${r.supplyRisk},${r.regulatoryRisk}`
  ).join('\n');
  downloadBlob(header + rows, `chemtrace_routes_${results.molecule.name.toLowerCase()}.csv`, 'text/csv');
}

export function downloadReagentsCSV(reagents: ReagentInfo[], moleculeName: string) {
  const header = 'Reagent,CAS,Supplier,Country,Price,Availability,Lead Days,Hazard,Geo Risk,Status,Export Ctrl\n';
  const rows = reagents.map(r =>
    `"${r.name}",${r.cas},"${r.supplier}",${r.country},"${r.price}",${r.availability},${r.leadDays},"${r.hazard}",${r.geoRisk},${r.status},${r.exportControlled ? 'Yes' : 'No'}`
  ).join('\n');
  downloadBlob(header + rows, `chemtrace_reagents_${moleculeName.toLowerCase()}.csv`, 'text/csv');
}

export function downloadJSON(results: PipelineResults) {
  downloadBlob(JSON.stringify(results, null, 2), `chemtrace_${results.molecule.name.toLowerCase()}.json`, 'application/json');
}

export function downloadCROBrief(results: PipelineResults) {
  const rec = results.routes.find(r => r.id === results.recommendedRouteId)!;
  const brief = `CRO SYNTHESIS BRIEF
Generated by ChemTrace — ${new Date().toISOString().slice(0, 10)}
${'═'.repeat(60)}

TARGET MOLECULE: ${results.molecule.name}
SMILES: ${results.molecule.smiles}
IUPAC: ${results.molecule.iupac}
MW: ${results.molecule.mw} g/mol
BATCH SIZE: ${results.batchSizeMg} mg
PRODUCTION LOCATION: ${results.location}

${'─'.repeat(60)}
RECOMMENDED ROUTE: ${rec.name}
STATUS: ${rec.status}
ESTIMATED YIELD: ${rec.yieldPercent}%
COST PER GRAM: £${rec.costPerGram}
BATCH COST ESTIMATE: £${rec.batchEstimate}

SYNTHESIS STEPS:
${rec.steps.map(s => `  ${s.number}. ${s.description}`).join('\n')}

REAGENTS: ${rec.reagents.join(', ')}

LITERATURE: ${rec.citation}

SUPPLY RISK: ${rec.supplyRisk}
REGULATORY RISK: ${rec.regulatoryRisk}
DECISION: ${rec.decisionReason}
`;
  downloadBlob(brief, `chemtrace_cro_brief_${results.molecule.name.toLowerCase()}.txt`, 'text/plain');
}

export function generateInvoiceData(route: SynthesisRoute, batchMg: number) {
  const items = route.reagentProcurement.map(r => {
    const priceMatch = r.price.match(/£([\d.]+)/);
    const unitPrice = priceMatch ? parseFloat(priceMatch[1]) : 0;
    const qty = Math.max(1, Math.ceil(batchMg / 500));
    return { reagent: r.name, cas: r.cas, supplier: r.supplier, unitPrice, qty, total: +(unitPrice * qty).toFixed(2) };
  });
  const subtotal = items.reduce((s, i) => s + i.total, 0);
  const vat = +(subtotal * 0.20).toFixed(2);
  return { items, subtotal: +subtotal.toFixed(2), vat, grandTotal: +(subtotal + vat).toFixed(2), invoiceNumber: `CT-${Date.now().toString(36).toUpperCase()}`, date: new Date().toISOString().slice(0, 10) };
}
