import { supabase } from '@/integrations/supabase/client';
import type {
  SynthesisRoute,
  ReagentInfo,
  RiskLevel,
  RouteStep,
} from '@/types/chemtrace';

export interface RetrosynthesisResponse {
  valid: boolean;
  canonical_smiles?: string;
  descriptors?: { formula?: string; mw?: number; rings?: number };
  engine?: string;
  cached?: boolean;
  routes?: Array<{
    id: string;
    name: string;
    score: number;
    yieldPercent: number;
    complexity?: number;
    decisionReason: string;
    startingMaterials: string[];
    steps: RouteStep[];
  }>;
  error?: string;
}

/** Heuristic: looks like a SMILES (not a plain English word/name). */
export function looksLikeSmiles(q: string): boolean {
  const s = q.trim();
  if (!s) return false;
  // Names are usually all letters / spaces / hyphens. SMILES contains brackets,
  // explicit bonds, ring digits, charges, or mixed-case atom symbols.
  if (/[\[\]()=#@+\-\\/.%]/.test(s)) return true;
  if (/\d/.test(s) && /[A-Za-z]/.test(s)) return true;
  // Mixed case organic subset like "CCO", "CC(C)O" — uppercase + lowercase atoms.
  if (/[A-Z]/.test(s) && /[a-z]/.test(s) && !/\s/.test(s)) return true;
  return false;
}

export async function runRetrosynthesis(
  smiles: string,
): Promise<RetrosynthesisResponse> {
  const { data, error } = await supabase.functions.invoke('retrosynthesis', {
    body: { smiles },
  });
  if (error) {
    return { valid: false, error: error.message ?? 'Engine unreachable' };
  }
  return data as RetrosynthesisResponse;
}

/** Default reagent procurement entry for an engine-suggested chemical. */
function defaultReagent(name: string): ReagentInfo {
  return {
    name,
    cas: '—',
    supplier: 'Sigma-Aldrich',
    country: 'Germany',
    price: 'See supplier',
    availability: 'Check supplier',
    leadDays: 5,
    hazard: 'Consult SDS',
    geoRisk: 'low' as RiskLevel,
    status: 'STANDARD',
    exportControlled: false,
  };
}

/** Convert engine output into the SynthesisRoute shape the UI already renders. */
export function adaptEngineRoutes(
  engineRoutes: NonNullable<RetrosynthesisResponse['routes']>,
  engine: string,
  location: string,
  batchMg: number,
  mw: number,
): SynthesisRoute[] {
  const batchG = batchMg / 1000;
  return engineRoutes.map((r, idx) => {
    const reagents = new Set<string>();
    r.startingMaterials.forEach(m => reagents.add(m));
    r.steps.forEach(s => {
      if (s.conditions?.reagents) {
        s.conditions.reagents.split(/[,;]/).map(x => x.trim()).filter(Boolean)
          .forEach(x => reagents.add(x));
      }
      if (s.conditions?.catalyst) reagents.add(s.conditions.catalyst);
      if (s.conditions?.solvent) reagents.add(s.conditions.solvent);
    });
    const reagentList = Array.from(reagents);
    const costPerGram = +(mw * 0.08 + 5 + (r.steps.length * 1.5)).toFixed(2);
    const status = r.score >= 0.8 ? 'APPROVED' : r.score >= 0.5 ? 'FLAGGED' : 'REJECTED';
    return {
      id: `R${idx + 1}`,
      name: r.name,
      status,
      score: r.score,
      yieldPercent: r.yieldPercent,
      costPerGram,
      batchEstimate: +(costPerGram * batchG).toFixed(2),
      steps: r.steps.map((s, j) => ({
        ...s,
        number: j + 1,
      })),
      reagents: reagentList,
      reagentProcurement: reagentList.map(defaultReagent),
      citation: `Computed by ${engine}. Routes are AI-generated proposals — verify against literature before scale-up.`,
      supplyRisk: 'low' as RiskLevel,
      regulatoryRisk: 'low' as RiskLevel,
      decisionReason: r.decisionReason,
      engine,
      aiGenerated: true,
      complexity: r.complexity,
      riskNotes: [
        {
          type: 'warning',
          text: `Route generated by an AI retrosynthesis model (${engine}) for ${location} production. Reaction conditions and precedents are model predictions, not experimentally verified. Cross-check key steps against primary literature.`,
        },
      ],
    };
  });
}