export interface MoleculeData {
  name: string;
  smiles: string;
  /** RDKit-canonicalised SMILES — the single internal representation. */
  canonicalSmiles?: string;
  iupac: string;
  mw: number;
  xlogp: number;
  hbd: number;
  rings: number;
  cid?: number;
  /** Data provenance — drives the verification badge in the UI. */
  source?: 'pubchem' | 'curated' | 'ai-inferred';
}

export type RiskLevel = 'low' | 'medium' | 'high';
export type RouteStatus = 'APPROVED' | 'FLAGGED' | 'REJECTED';

export interface RouteStep {
  number: number;
  description: string;
  smiles?: string;
  /** Reaction SMILES "reactants>>product" when supplied by the engine. */
  reactionSmiles?: string;
  /** Predicted reaction conditions for this step. */
  conditions?: ReactionConditions;
  /** Per-step confidence score (0–1) from the retrosynthesis model. */
  confidence?: number;
}

export interface ReactionConditions {
  solvent?: string;
  catalyst?: string;
  reagents?: string;
  temperature?: string;
  pressure?: string;
  time?: string;
  confidence?: number;
  source?: string;
  precedents?: number;
}

export interface ReagentInfo {
  name: string;
  cas: string;
  supplier: string;
  country: string;
  price: string;
  availability: string;
  leadDays: number;
  hazard: string;
  geoRisk: RiskLevel;
  status: 'PREFERRED' | 'STANDARD' | 'RESTRICTED' | 'BLOCKED';
  exportControlled: boolean;
  /** Optional direct link to the supplier product page. If omitted, the UI builds a search URL from the supplier name + CAS. */
  productUrl?: string;
  /** Optional pricing breakdown for clarity (unit price, pack size, currency). */
  unitPrice?: number;
  packSize?: string;
  priceCurrency?: 'GBP' | 'USD' | 'EUR';
}

export interface SynthesisRoute {
  id: string;
  name: string;
  status: RouteStatus;
  score: number;
  yieldPercent: number;
  costPerGram: number;
  batchEstimate: number;
  steps: RouteStep[];
  reagents: string[];
  reagentProcurement: ReagentInfo[];
  citation: string;
  supplyRisk: RiskLevel;
  regulatoryRisk: RiskLevel;
  decisionReason: string;
  riskNotes?: { type: 'error' | 'warning' | 'info'; text: string }[];
  /** Identifies the engine that produced this route (e.g. "llm-gemini-v1", "curated"). */
  engine?: string;
  /** True when the route was generated by an AI model rather than literature/curation. */
  aiGenerated?: boolean;
  /** Estimated synthetic complexity (0–10, higher = more complex). */
  complexity?: number;
}

export interface RegulatoryFramework {
  location: string;
  body: string;
  regulations: string[];
  preferredRegions: string[];
  jurisdictionNotes: string;
}

export interface PipelineResults {
  molecule: MoleculeData;
  location: string;
  regulatory: RegulatoryFramework;
  routes: SynthesisRoute[];
  recommendedRouteId: string;
  agentExplanation: string;
  batchSizeMg: number;
}

export interface ChatMessage {
  role: 'user' | 'agent';
  content: string;
}
